version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=mysql://singleuser:singlepassword@mysql:3306/mysql
        - REDIS_URL=redis://redis:6379
        - RPC_URL=http://solana-test-validator:8899
        - NEXT_PUBLIC_CLIENTVAR=jwdKwUo0FG11oQ3fRYxijZRHVY7Sq2VC
    ports:
      - "3000:3000"
    environment:
      - HOSTNAME=0.0.0.0
    depends_on:
      - mysql
      - redis
      - solana-test-validator
    networks:
      - app-network
    command: bun run dev:ui
    develop:
      watch:
        - action: sync
          path: src
          target: /app/src
        - action: rebuild
          path: "package.json"
          target: /app/package.json
        - action: rebuild
          path: "tsconfig.json"
          target: /app/tsconfig.json
        - action: rebuild
          path: "next.config.js"
          target: /app/next.config.js
        - action: rebuild
          path: "Dockerfile"
          target: /app/Dockerfile
  solana-test-validator:
    image: ghcr.io/beeman/solana-test-validator:latest
    ports:
      - "8899:8899"
      - "8900:8900"
    command: solana-test-validator --reset
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=singleuser
      - MYSQL_PASSWORD=singlepassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
